### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by skycatminepokie** [Xiaomckedou233/SlipperyPlus#1]
Hello! I just wanted to know, does this work for players in boats when only installed on the server side? If so, I'd be interested in using the mixins in my [mod](https://github.com/skycatminepokie/mystical). I tried getting this effect for just boats by overwriting BoatEntity#getNearbySlipperiness, but it didn't work, and I'm wondering if it's because I didn't mess with the velocity thing or if maybe vehicles are just controlled by the client. Thanks!

**Comment by Xiaomckedou233** [comment]
It seems that vehicles are just controlled by the client side, and may not work when installed only on the server side.

**Comment by Xiaomckedou233** [comment]
Actually, in my mod it also doesn't work when only installed on the server side.
