### ISSUE TITLE
[question] friction amount

### ISSUE THREAD

**Issue by krispyking24** [Xiaomckedou233/SlipperyPlus#2]
the [previous version of the mod](https://www.curseforge.com/minecraft/mc-mods/slippery-mod) had 2 versions one with a small amount of friction and the other with no friction at all, which is this mod based on?

**Comment by Xiaomckedou233** [comment]
This mod is based on the version with a small amount of friction

**Comment by Xiaomckedou233** [comment]
If you prefer the frictionless version, I can certainly build one for you.

**Comment by krispyking24** [comment]
ok thank you for clarifying that, it might be a good idea to either say that in the description or maybe make a config in game for it, i think i know how to remove the friction if i were to want to but thanks for the offer

**Comment by Xiaomckedou233** [comment]
After seeing your question, I've updated the description on Modrinth to include this information. I'll also work on creating a configuration interface when I have some time.
